# Where: .github/workflows/build.yml
# What: プラグインビルド用GitHub Actionsワークフロー
# Why: テストとビルドを自動化しmainブランチおよびタグ作成時に実行するため

name: Build Plugin

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Gradle wrapper executable
        if: runner.os == 'Linux'
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        if: ${{ env.ACT != 'true' }}
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew --no-daemon test

      - name: Verify plugin
        run: ./gradlew --no-daemon verifyPlugin

      - name: Build plugin distribution
        run: ./gradlew --no-daemon buildPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-distribution
          path: build/distributions/*.zip
