# Where: .github/workflows/build.yml
# What: プラグインビルド用GitHub Actionsワークフロー
# Why: テストとビルドを自動化しタグ作成時のみ実行するため

name: Build Plugin

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make Gradle wrapper executable
        if: runner.os == 'Linux'
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle cache
        # setup-gradle@v4 は Gradle Wrapper の検証機能を内包する
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew --no-daemon test

      - name: Verify plugin
        run: ./gradlew --no-daemon verifyPlugin

      - name: Build plugin distribution
        run: ./gradlew --no-daemon buildPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-distribution
          path: build/distributions/*.zip
